### PR TITLE
First test of a bigpicture for LCMS

### PR DESCRIPTION
**Pull request by lecorguille**
@workflow4metabolomics/coreteam 

What do you think about this first bigpicture of LCMS:
lc-ms-bigpicture

Some part can be easily copy/paste to the GCMS and NMR workflow.

With that, we will be able to crop some part to refresh our picture within the different tool `<help>` section, within our training materials and posters.

It was drawn using [yEd](https://www.yworks.com/products/yed) a multi-plateform Graph Editor. When you are used to it, it's rather easy to use

This tool saves some light [text files](https://github.com/workflow4metabolomics/workflow4metabolomics/blob/workflow_bigpicture/images/workflow/LCMS-bigpicture.graphml) which can be easily push to GitHub.

I also generated an export of my [palette file](https://github.com/workflow4metabolomics/workflow4metabolomics/blob/workflow_bigpicture/images/workflow/palette_w4m.graphml) you will be able to import in yEd with the different elements used in this picture: tool, optional tool, noodle (node) and categorie box.

### CODE REVIEW

**Comment by bgruening** [comment]
Great figure @lecorguille!

**Comment by fgiacomoni** [comment]
Great panorama !! The only tiny remark concerning the start of the global workflow. Setting  in parallel the two ways (xcmsSet and xcmsSet(s) + xcms.merger) before the "group" tool should be nice. Thanks Gildas !

**Comment by lecorguille** [comment]
@fgiacomoni Are you imagine 2 boxes? Or 2 boxes in a the box?

**Comment by lecorguille** [comment]
@fgiacomoni Done: https://github.com/workflow4metabolomics/workflow4metabolomics/pull/13

**Pull request merged**
